
"@context":

ontologies:

  - id: aba_uberon
    preferredPrefix: ABA
    title: Allan Brain Atlas Uberon Mashup
    description: >
      Application ontology combining ontologised versions of ABA structureGraphs with Uberon
    uri: http://purl.obolibrary.org/obo/aba-uberon.owl
    base_uri:
      - http://purl.obolibrary.org/obo/UBERON_
      - http://purl.obolibrary.org/obo/MBA_
      - http://purl.obolibrary.org/obo/HBA_
      - http://purl.obolibrary.org/obo/DMBA_
      - http://purl.obolibrary.org/obo/DHBA_
      - http://purl.obolibrary.org/obo/PBA_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    reasoner: EL
    oboSlims: false
    ontology_purl : file:///opt/ols/ontologies/aba_uberon.owl
